name : "Next JS Linter Check"

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Changing Directory
        uses: cd assigment_4

      - name: Install dependencies
        run:  npm install

      - name: Run Next.js linter
        run: npm run lint
          
