name : "Next JS Linter Check"

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run:  npm install
        working-directory: assigment_4

      - name: Run Next.js linter
        run: npm run lint
        working-directory: assigment_4
          
